// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itdljhjktjxogjjutteq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZGxqaGprdGp4b2dqanV0dGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNTU0NzcsImV4cCI6MjA2MjkzMTQ3N30.Rt556NIaImZUoMF_1DPBtf4v3JXvadoPfZfr6qNhlUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);